ALTER TABLE attributes_camerastream MODIFY STR_KEY VARCHAR(100) NOT NULL;
ALTER TABLE attributes_camerastream MODIFY STR_VALUE VARCHAR(100) NOT NULL;
ALTER TABLE attributes_surveillance MODIFY STR_KEY VARCHAR(100) NOT NULL;
ALTER TABLE attributes_surveillance MODIFY STR_VALUE VARCHAR(100) NOT NULL;