ALTER TABLE servers ADD IS_MASTER TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE servers ADD HAS_SERVICE_CAMERASTREAM TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE servers ADD HAS_SERVICE_SURVEILLANCE TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE servers ADD STR_URL_MASTER VARCHAR(100);
ALTER TABLE servers ADD STR_ID_MASTER VARCHAR(100);
ALTER TABLE servers ADD STR_USERNAME_MASTER VARCHAR(100);
ALTER TABLE servers ADD STR_PASSWORD_MASTER VARCHAR(100);