CREATE TABLE IF NOT EXISTS roles (
	NR_ID BINARY(16) NOT NULL,
	STR_NAME VARCHAR(20),
	CONSTRAINT pk_roles
		PRIMARY KEY ( NR_ID )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS users (
	NR_ID BINARY(16) NOT NULL,
	STR_USERNAME VARCHAR(100),
	STR_EMAIL VARCHAR(100),
	STR_PASSWORD VARCHAR(100),
	STATUS_VERIFIED TINYINT(1) NOT NULL DEFAULT 0,
	JSON_DATA JSON CHECK (JSON_VALID(json_data)),
	CONSTRAINT pk_users
		PRIMARY KEY ( NR_ID ),
	UNIQUE KEY uk_username ( STR_USERNAME ),
	UNIQUE KEY uk_email ( STR_EMAIL )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS user_roles (
	NR_USER_ID BINARY(16) NOT NULL,
	NR_ROLE_ID BINARY(16) NOT NULL,
	CONSTRAINT pk_user_roles_id
		PRIMARY KEY ( NR_USER_ID, NR_ROLE_ID )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS user_forgot_password_tokens (
	NR_ID BINARY(16) NOT NULL,
	NR_USER_ID BINARY(16) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS user_verification_tokens (
	NR_ID BINARY(16) NOT NULL,
	NR_USER_ID BINARY(16) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS servers (
	NR_ID BINARY(16) NOT NULL,
	DATE_CREATED TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	STR_NAME VARCHAR(100),
	STR_URL VARCHAR(100),
	STR_USERNAME VARCHAR(100),
	STR_PASSWORD VARCHAR(100),
	STR_URL_CAMERASTREAM VARCHAR(100),
	STR_USERNAME_CAMERASTREAM VARCHAR(100),
	STR_PASSWORD_CAMERASTREAM VARCHAR(100),
	STR_STATUS VARCHAR(20),
	JSON_DATA JSON CHECK (JSON_VALID(json_data)),
	CONSTRAINT pk_servers
		PRIMARY KEY ( NR_ID )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS attributes_camerastream (
	NR_ID VARCHAR(36) NOT NULL DEFAULT UUID(),
	NR_SERVER_ID BINARY(16) NOT NULL,
	STR_KEY VARCHAR(30) NOT NULL,
	STR_VALUE VARCHAR(30) NOT NULL,
	CONSTRAINT pk_attributes_camerastream_id
		PRIMARY KEY ( NR_ID, NR_SERVER_ID )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS attributes_surveillance (
	NR_ID VARCHAR(36) NOT NULL DEFAULT UUID(),
	NR_SERVER_ID BINARY(16) NOT NULL,
	STR_KEY VARCHAR(30) NOT NULL,
	STR_VALUE VARCHAR(30) NOT NULL,
	CONSTRAINT pk_attributes_surveillance_id
		PRIMARY KEY ( NR_ID, NR_SERVER_ID )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
